# ==================================================================== #
# TITLE                                                                #
# microorganisms: An R Package for Microbial Taxonomy Reference Data   #
#                                                                      #
# SOURCE                                                               #
# https://github.com/msberends/microorganisms                          #
#                                                                      #
# This R package is free software; you can freely use and distribute   #
# it for both personal and commercial purposes under the terms of the  #
# GNU General Public License version 2.0 (GNU GPL-2), as published by  #
# the Free Software Foundation.                                        #
# ==================================================================== #

on:
  pull_request:
    # run in each PR in this repo
    branches: '**'
  push:
    branches: '**'

name: check-recent

jobs:
  R-code-check:
    runs-on: ${{ matrix.config.os }}

    continue-on-error: ${{ matrix.config.allowfail }}

    name: ${{ matrix.config.os }} (R-${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # current development version:
          - {os: macOS-latest,   r: 'devel', allowfail: false}
          - {os: windows-latest, r: 'devel', allowfail: false}
          - {os: ubuntu-latest,  r: 'devel', allowfail: false}

          # current 'release' version:
          - {os: macOS-latest,   r: '4.2', allowfail: false}
          - {os: windows-latest, r: '4.2', allowfail: false}
          - {os: ubuntu-latest,  r: '4.2', allowfail: false}

          # older versions (see also check-old.yaml for even older versions):
          - {os: ubuntu-latest, r: '4.1', allowfail: false}
          - {os: ubuntu-latest, r: '4.0', allowfail: false}
          - {os: ubuntu-latest, r: '3.6', allowfail: false}
          - {os: ubuntu-latest, r: '3.5', allowfail: false} # when a new R releases, this one has to move to check-old.yaml

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          # use RStudio Package Manager to quickly install packages
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        env:
          _R_CHECK_LENGTH_1_CONDITION_: verbose
          _R_CHECK_LENGTH_1_LOGIC2_: verbose
          # during 'R CMD check', R_LIBS_USER will be overwritten, so:
          R_LIBS_USER_GH_ACTIONS: ${{ env.R_LIBS_USER }}
          R_RUN_TINYTEST: true

      - name: Show tinytest output
        if: always()
        run: |
          find . -name 'tinytest.Rout*' -exec cat '{}' \; || true
        shell: bash
